name = "asguard-interceptor"
main = "src/index.ts"
compatibility_date = "2023-10-01"

# Bind a KV Namespace for the Global Blocklist
kv_namespaces = [
  { binding = "ASGUARD_GLOBAL_BLOCKLIST", id = "<YOUR_KV_NAMESPACE_ID>" }
]
