name = "asguard-interceptor"
main = "src/index.ts"
compatibility_date = "2023-10-01"

# Bind a KV Namespace for the Global Blocklist
kv_namespaces = [
  { binding = "ASGUARD_BLACKLIST", id = "53ed082bcd0f465c94f08626c97160ca" },
  { binding = "ASGUARD_TELEMETRY", id = "9141c0fd3eb44d3c84375f418c716495" }
]

[ai]
binding = "AI"
